"""Report domain model."""
from dataclasses import dataclass
from typing import Any


@dataclass
class Report:
    """Incident report generated by the agent; stored per session."""

    id: str
    session_id: str
    content: str
    created_at: str

    def to_api(self, include_content: bool = True) -> dict[str, Any]:
        """API response shape: id, session_id, created_at; optional content."""
        out: dict[str, Any] = {
            "id": self.id,
            "session_id": self.session_id,
            "created_at": self.created_at,
        }
        if include_content:
            out["content"] = self.content
        return out
